moved tf definitions from commons to separate global folder
clouduct/terraform-template pull request #3
Opened 2018-06-19 20:29 UTC by AgnesK

2018-06-19 20:53 UTC, kontrafiktion requested changes
clouduct-tf ist schon so umgebaut, dass es als erstes Argument das „Verb“ erwartet, also

clouduct-tf apply global build compute

und nicht 

clouduct-tf global build compute apply

2018-06-20 11:28 UTC, kontrafiktion approved these changes

2018-06-20 11:33 UTC, karingross approved these changes

2018-06-20 11:33 UTC, karingross approved these changes

2018-06-20 12:02 UTC, merged